//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExosHeroesManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HeroImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeroImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExosHeroesManager.HeroImages", typeof(HeroImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Adams {
            get {
                object obj = ResourceManager.GetObject("Adams", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Adams_Cunning {
            get {
                object obj = ResourceManager.GetObject("Adams_Cunning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alexei {
            get {
                object obj = ResourceManager.GetObject("Alexei", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Anastasia {
            get {
                object obj = ResourceManager.GetObject("Anastasia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Anastasia_Ignite {
            get {
                object obj = ResourceManager.GetObject("Anastasia_Ignite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Annie {
            get {
                object obj = ResourceManager.GetObject("Annie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Annie_Wandering_Flamemaster {
            get {
                object obj = ResourceManager.GetObject("Annie_Wandering_Flamemaster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] April {
            get {
                object obj = ResourceManager.GetObject("April", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] April_Millennial_Star {
            get {
                object obj = ResourceManager.GetObject("April_Millennial_Star", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Astarte {
            get {
                object obj = ResourceManager.GetObject("Astarte", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Awakened_Zeon {
            get {
                object obj = ResourceManager.GetObject("Awakened_Zeon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Awakened_Zeon_Twilight_Sword {
            get {
                object obj = ResourceManager.GetObject("Awakened_Zeon_Twilight_Sword", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Baileysh {
            get {
                object obj = ResourceManager.GetObject("Baileysh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Baileysh_Rothbrok {
            get {
                object obj = ResourceManager.GetObject("Baileysh_Rothbrok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Baraka {
            get {
                object obj = ResourceManager.GetObject("Baraka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Baraka_Black_Moon {
            get {
                object obj = ResourceManager.GetObject("Baraka_Black_Moon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bathory {
            get {
                object obj = ResourceManager.GetObject("Bathory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bathory_Descendant_of_Spirits {
            get {
                object obj = ResourceManager.GetObject("Bathory_Descendant_of_Spirits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bayer {
            get {
                object obj = ResourceManager.GetObject("Bayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Benten {
            get {
                object obj = ResourceManager.GetObject("Benten", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Benten_Wings_of_Anguish {
            get {
                object obj = ResourceManager.GetObject("Benten_Wings_of_Anguish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bernadette {
            get {
                object obj = ResourceManager.GetObject("Bernadette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bernadette_Melting_Ice {
            get {
                object obj = ResourceManager.GetObject("Bernadette_Melting_Ice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bernavas {
            get {
                object obj = ResourceManager.GetObject("Bernavas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bernavas_Fully_Bloomed_Blue_Cotton {
            get {
                object obj = ResourceManager.GetObject("Bernavas_Fully_Bloomed_Blue_Cotton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bernavas_Grey_Light_Princess {
            get {
                object obj = ResourceManager.GetObject("Bernavas_Grey_Light_Princess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Berol {
            get {
                object obj = ResourceManager.GetObject("Berol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Bongkoos {
            get {
                object obj = ResourceManager.GetObject("Bongkoos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Brook {
            get {
                object obj = ResourceManager.GetObject("Brook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Brook_The_Strongest_Sheep {
            get {
                object obj = ResourceManager.GetObject("Brook_The_Strongest_Sheep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Buck {
            get {
                object obj = ResourceManager.GetObject("Buck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Carlos {
            get {
                object obj = ResourceManager.GetObject("Carlos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Carrie {
            get {
                object obj = ResourceManager.GetObject("Carrie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Carrie_Young_Empress_of_Brunn {
            get {
                object obj = ResourceManager.GetObject("Carrie_Young_Empress_of_Brunn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chati {
            get {
                object obj = ResourceManager.GetObject("Chati", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Chati_Cat_Guardian_Knight {
            get {
                object obj = ResourceManager.GetObject("Chati_Cat_Guardian_Knight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Colin {
            get {
                object obj = ResourceManager.GetObject("Colin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Colossal_Drill_MK1 {
            get {
                object obj = ResourceManager.GetObject("Colossal_Drill_MK1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Corgi {
            get {
                object obj = ResourceManager.GetObject("Corgi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Corgi_Song_of_Atonement {
            get {
                object obj = ResourceManager.GetObject("Corgi_Song_of_Atonement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Cybele {
            get {
                object obj = ResourceManager.GetObject("Cybele", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dana {
            get {
                object obj = ResourceManager.GetObject("Dana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dana_Shining_Summer {
            get {
                object obj = ResourceManager.GetObject("Dana_Shining_Summer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] David_Johnson {
            get {
                object obj = ResourceManager.GetObject("David_Johnson", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Degas {
            get {
                object obj = ResourceManager.GetObject("Degas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Degas_Beach_by_the_Blue_Sea {
            get {
                object obj = ResourceManager.GetObject("Degas_Beach_by_the_Blue_Sea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Deva {
            get {
                object obj = ResourceManager.GetObject("Deva", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Deva_Red_Outlaw {
            get {
                object obj = ResourceManager.GetObject("Deva_Red_Outlaw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dorka {
            get {
                object obj = ResourceManager.GetObject("Dorka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Dorka_CODE_MELPOMENE {
            get {
                object obj = ResourceManager.GetObject("Dorka_CODE_MELPOMENE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Duncan {
            get {
                object obj = ResourceManager.GetObject("Duncan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Emma {
            get {
                object obj = ResourceManager.GetObject("Emma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Emma_Saint_Wests_Second_Queen {
            get {
                object obj = ResourceManager.GetObject("Emma_Saint_Wests_Second_Queen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fergie {
            get {
                object obj = ResourceManager.GetObject("Fergie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Firis {
            get {
                object obj = ResourceManager.GetObject("Firis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Freesia {
            get {
                object obj = ResourceManager.GetObject("Freesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gale {
            get {
                object obj = ResourceManager.GetObject("Gale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Garff {
            get {
                object obj = ResourceManager.GetObject("Garff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Garff_Guardian_of_the_East {
            get {
                object obj = ResourceManager.GetObject("Garff_Guardian_of_the_East", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Garff_The_White_Warlord {
            get {
                object obj = ResourceManager.GetObject("Garff_The_White_Warlord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Garlond {
            get {
                object obj = ResourceManager.GetObject("Garlond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Garlond_Shadow_of_the_Blue_Waves {
            get {
                object obj = ResourceManager.GetObject("Garlond_Shadow_of_the_Blue_Waves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Glenn {
            get {
                object obj = ResourceManager.GetObject("Glenn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Glenn_Summer_Guy {
            get {
                object obj = ResourceManager.GetObject("Glenn_Summer_Guy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Godin {
            get {
                object obj = ResourceManager.GetObject("Godin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Griesel {
            get {
                object obj = ResourceManager.GetObject("Griesel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Guter {
            get {
                object obj = ResourceManager.GetObject("Guter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hawkeye {
            get {
                object obj = ResourceManager.GetObject("Hawkeye", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hekin {
            get {
                object obj = ResourceManager.GetObject("Hekin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hekin_Squishy {
            get {
                object obj = ResourceManager.GetObject("Hekin_Squishy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Heowon {
            get {
                object obj = ResourceManager.GetObject("Heowon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hinder {
            get {
                object obj = ResourceManager.GetObject("Hinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Iden {
            get {
                object obj = ResourceManager.GetObject("Iden", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Iden_Beat_Shooter {
            get {
                object obj = ResourceManager.GetObject("Iden_Beat_Shooter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Iris {
            get {
                object obj = ResourceManager.GetObject("Iris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Iris_Holiday_at_the_White_Ocean {
            get {
                object obj = ResourceManager.GetObject("Iris_Holiday_at_the_White_Ocean", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ivan {
            get {
                object obj = ResourceManager.GetObject("Ivan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jean {
            get {
                object obj = ResourceManager.GetObject("Jean", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jean_Desperado {
            get {
                object obj = ResourceManager.GetObject("Jean_Desperado", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jinai {
            get {
                object obj = ResourceManager.GetObject("Jinai", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jinai_Supreme_Queen {
            get {
                object obj = ResourceManager.GetObject("Jinai_Supreme_Queen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jinai_White_Flower_of_Healing {
            get {
                object obj = ResourceManager.GetObject("Jinai_White_Flower_of_Healing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jinn {
            get {
                object obj = ResourceManager.GetObject("Jinn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jinn_Gaze_of_the_White_Gull {
            get {
                object obj = ResourceManager.GetObject("Jinn_Gaze_of_the_White_Gull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jinn_Soft_Silver_Hair {
            get {
                object obj = ResourceManager.GetObject("Jinn_Soft_Silver_Hair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] John_Donk {
            get {
                object obj = ResourceManager.GetObject("John_Donk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] John_Donk_Successor {
            get {
                object obj = ResourceManager.GetObject("John_Donk_Successor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Karin {
            get {
                object obj = ResourceManager.GetObject("Karin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kaya {
            get {
                object obj = ResourceManager.GetObject("Kaya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kaya_Heavenly_Voice {
            get {
                object obj = ResourceManager.GetObject("Kaya_Heavenly_Voice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kinberra {
            get {
                object obj = ResourceManager.GetObject("Kinberra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kirina {
            get {
                object obj = ResourceManager.GetObject("Kirina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kylock {
            get {
                object obj = ResourceManager.GetObject("Kylock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kylock_Requiem_Shaman {
            get {
                object obj = ResourceManager.GetObject("Kylock_Requiem_Shaman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lang {
            get {
                object obj = ResourceManager.GetObject("Lang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Leger {
            get {
                object obj = ResourceManager.GetObject("Leger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Leger_Priestess_of_the_Moonlight {
            get {
                object obj = ResourceManager.GetObject("Leger_Priestess_of_the_Moonlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lepin {
            get {
                object obj = ResourceManager.GetObject("Lepin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lepin_Fairy_Queen_of_Protection {
            get {
                object obj = ResourceManager.GetObject("Lepin_Fairy_Queen_of_Protection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Liechtenstein {
            get {
                object obj = ResourceManager.GetObject("Liechtenstein", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Liffy {
            get {
                object obj = ResourceManager.GetObject("Liffy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Liffy_Astral_Idol {
            get {
                object obj = ResourceManager.GetObject("Liffy_Astral_Idol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Luke {
            get {
                object obj = ResourceManager.GetObject("Luke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Luke_Most_Reliable {
            get {
                object obj = ResourceManager.GetObject("Luke_Most_Reliable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Luna {
            get {
                object obj = ResourceManager.GetObject("Luna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Luna_Blue_Moon_of_Tropical_Night {
            get {
                object obj = ResourceManager.GetObject("Luna_Blue_Moon_of_Tropical_Night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lyungen {
            get {
                object obj = ResourceManager.GetObject("Lyungen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lyungen_Red_Baker {
            get {
                object obj = ResourceManager.GetObject("Lyungen_Red_Baker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lyungen_Transcendent_Spirit {
            get {
                object obj = ResourceManager.GetObject("Lyungen_Transcendent_Spirit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Magi {
            get {
                object obj = ResourceManager.GetObject("Magi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Magi_Jude_Turner {
            get {
                object obj = ResourceManager.GetObject("Magi_Jude_Turner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mahar {
            get {
                object obj = ResourceManager.GetObject("Mahar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mahar_Displaced_Wolf {
            get {
                object obj = ResourceManager.GetObject("Mahar_Displaced_Wolf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mahar_Eastern_Monarchy {
            get {
                object obj = ResourceManager.GetObject("Mahar_Eastern_Monarchy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Melissa {
            get {
                object obj = ResourceManager.GetObject("Melissa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Metron {
            get {
                object obj = ResourceManager.GetObject("Metron", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Minea {
            get {
                object obj = ResourceManager.GetObject("Minea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mirrty {
            get {
                object obj = ResourceManager.GetObject("Mirrty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Misty {
            get {
                object obj = ResourceManager.GetObject("Misty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Monica {
            get {
                object obj = ResourceManager.GetObject("Monica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Monica_Supernova {
            get {
                object obj = ResourceManager.GetObject("Monica_Supernova", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Morris {
            get {
                object obj = ResourceManager.GetObject("Morris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Morris_Extremely_Stubborn {
            get {
                object obj = ResourceManager.GetObject("Morris_Extremely_Stubborn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nemeris {
            get {
                object obj = ResourceManager.GetObject("Nemeris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nemeris_Black_Prince {
            get {
                object obj = ResourceManager.GetObject("Nemeris_Black_Prince", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Neomi {
            get {
                object obj = ResourceManager.GetObject("Neomi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Neomi_Dominator {
            get {
                object obj = ResourceManager.GetObject("Neomi_Dominator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nermash {
            get {
                object obj = ResourceManager.GetObject("Nermash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nero {
            get {
                object obj = ResourceManager.GetObject("Nero", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nika {
            get {
                object obj = ResourceManager.GetObject("Nika", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Nika_Violet_Sound {
            get {
                object obj = ResourceManager.GetObject("Nika_Violet_Sound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Obellia {
            get {
                object obj = ResourceManager.GetObject("Obellia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Oos {
            get {
                object obj = ResourceManager.GetObject("Oos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Otard {
            get {
                object obj = ResourceManager.GetObject("Otard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Otard_Dominator_of_Battle {
            get {
                object obj = ResourceManager.GetObject("Otard_Dominator_of_Battle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pan {
            get {
                object obj = ResourceManager.GetObject("Pan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pitbull {
            get {
                object obj = ResourceManager.GetObject("Pitbull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Prithiof {
            get {
                object obj = ResourceManager.GetObject("Prithiof", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rachel {
            get {
                object obj = ResourceManager.GetObject("Rachel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rachel_Executor_of_Battlefield {
            get {
                object obj = ResourceManager.GetObject("Rachel_Executor_of_Battlefield", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rachel_Successor_to_the_Throne {
            get {
                object obj = ResourceManager.GetObject("Rachel_Successor_to_the_Throne", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ramge {
            get {
                object obj = ResourceManager.GetObject("Ramge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ramge_Heir_to_the_Throne {
            get {
                object obj = ResourceManager.GetObject("Ramge_Heir_to_the_Throne", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ramge_Misty {
            get {
                object obj = ResourceManager.GetObject("Ramge_Misty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Reedmarie {
            get {
                object obj = ResourceManager.GetObject("Reedmarie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Reedmarie_Navy_Admiral {
            get {
                object obj = ResourceManager.GetObject("Reedmarie_Navy_Admiral", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rera {
            get {
                object obj = ResourceManager.GetObject("Rera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rera_Guardian_of_the_Minds_Eye {
            get {
                object obj = ResourceManager.GetObject("Rera_Guardian_of_the_Minds_Eye", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rera_Marinehawk {
            get {
                object obj = ResourceManager.GetObject("Rera_Marinehawk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rienor {
            get {
                object obj = ResourceManager.GetObject("Rienor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Risis {
            get {
                object obj = ResourceManager.GetObject("Risis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rood {
            get {
                object obj = ResourceManager.GetObject("Rood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rudley {
            get {
                object obj = ResourceManager.GetObject("Rudley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rudley_Vagabond_Swordsman {
            get {
                object obj = ResourceManager.GetObject("Rudley_Vagabond_Swordsman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sabrina {
            get {
                object obj = ResourceManager.GetObject("Sabrina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sabrina_El_Dorado {
            get {
                object obj = ResourceManager.GetObject("Sabrina_El_Dorado", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scarlet {
            get {
                object obj = ResourceManager.GetObject("Scarlet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scarlet_Hotter_than_the_Sun {
            get {
                object obj = ResourceManager.GetObject("Scarlet_Hotter_than_the_Sun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Schmid {
            get {
                object obj = ResourceManager.GetObject("Schmid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Schmid_Grand_Duke_of_Dark_Blood {
            get {
                object obj = ResourceManager.GetObject("Schmid_Grand_Duke_of_Dark_Blood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sefer {
            get {
                object obj = ResourceManager.GetObject("Sefer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Seir {
            get {
                object obj = ResourceManager.GetObject("Seir", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Seo_A {
            get {
                object obj = ResourceManager.GetObject("Seo_A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sernando {
            get {
                object obj = ResourceManager.GetObject("Sernando", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sharpei {
            get {
                object obj = ResourceManager.GetObject("Sharpei", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shell {
            get {
                object obj = ResourceManager.GetObject("Shell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shell_Artist_of_Death {
            get {
                object obj = ResourceManager.GetObject("Shell_Artist_of_Death", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shufraken {
            get {
                object obj = ResourceManager.GetObject("Shufraken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shufraken_Dragon_Emperor {
            get {
                object obj = ResourceManager.GetObject("Shufraken_Dragon_Emperor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Spica {
            get {
                object obj = ResourceManager.GetObject("Spica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Talia {
            get {
                object obj = ResourceManager.GetObject("Talia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Talia_Prophet_of_the_Sun {
            get {
                object obj = ResourceManager.GetObject("Talia_Prophet_of_the_Sun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tantalo {
            get {
                object obj = ResourceManager.GetObject("Tantalo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tantalo_Dignified {
            get {
                object obj = ResourceManager.GetObject("Tantalo_Dignified", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tereia {
            get {
                object obj = ResourceManager.GetObject("Tereia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Topaki {
            get {
                object obj = ResourceManager.GetObject("Topaki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Uloom {
            get {
                object obj = ResourceManager.GetObject("Uloom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Uloom_Black_and_White_Ogre {
            get {
                object obj = ResourceManager.GetObject("Uloom_Black_and_White_Ogre", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Uloom_Golden_Eyed_Ogre {
            get {
                object obj = ResourceManager.GetObject("Uloom_Golden-Eyed_Ogre", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Valarr {
            get {
                object obj = ResourceManager.GetObject("Valarr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Valarr_Black_Wolf {
            get {
                object obj = ResourceManager.GetObject("Valarr_Black_Wolf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Valarr_Knight_of_Black_Sword {
            get {
                object obj = ResourceManager.GetObject("Valarr_Knight_of_Black_Sword", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Valentina {
            get {
                object obj = ResourceManager.GetObject("Valentina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Valentina_Princesss_Vacation {
            get {
                object obj = ResourceManager.GetObject("Valentina_Princesss_Vacation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Venato {
            get {
                object obj = ResourceManager.GetObject("Venato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Vinity {
            get {
                object obj = ResourceManager.GetObject("Vinity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Weiler {
            get {
                object obj = ResourceManager.GetObject("Weiler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wilkes {
            get {
                object obj = ResourceManager.GetObject("Wilkes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wilkes_Screaming_Soul {
            get {
                object obj = ResourceManager.GetObject("Wilkes_Screaming_Soul", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Xiakhan {
            get {
                object obj = ResourceManager.GetObject("Xiakhan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Xiakhan_Blue_Dragons_Descent {
            get {
                object obj = ResourceManager.GetObject("Xiakhan_Blue_Dragons_Descent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yao {
            get {
                object obj = ResourceManager.GetObject("Yao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yao_Girls_Summer {
            get {
                object obj = ResourceManager.GetObject("Yao_Girls_Summer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Yorm {
            get {
                object obj = ResourceManager.GetObject("Yorm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Zarienne {
            get {
                object obj = ResourceManager.GetObject("Zarienne", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Zarienne_Bullet_of_Protection {
            get {
                object obj = ResourceManager.GetObject("Zarienne_Bullet_of_Protection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Zeon {
            get {
                object obj = ResourceManager.GetObject("Zeon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Zeon_Rood {
            get {
                object obj = ResourceManager.GetObject("Zeon_Rood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Zeradin {
            get {
                object obj = ResourceManager.GetObject("Zeradin", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
